---
version: '3.4'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.3
    ports:
     - "8080:8080"
     - "50051:50051"
    volumes:
     -./weaviate_data:/var/lib/weaviate
    environment:
     QUERY_DEFAULTS_LIMIT: 25
     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
     DEFAULT_VECTORIZER_MODULE: 'text2vec-google'
     ENABLE_MODULES: 'text2vec-google,generative-google'
     GOOGLE_API_KEY: ${GEMINI_API_KEY} # Pass the API key from the.env file
     CLUSTER_HOSTNAME: 'node1'